# Generated by Django 5.0.6 on 2024-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0008_alter_cart_qty_alter_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'cpu'), (2, 'graphic-card'), (3, 'motherboard')], verbose_name='category'),
        ),
    ]
